In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


from torch import nn, Tensor

In [2]:
sentences = [
    "I like eggs and ham.",
    "I love chocolate and bunnies.",
    "I hate onions."
]

In [3]:
MAX_VOCAB_SIZE = 20_000
tokenizer = Tokenizer(num_words = MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
sequences

[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]

In [4]:
tokenizer.word_index

{'i': 1,
 'and': 2,
 'like': 3,
 'eggs': 4,
 'ham': 5,
 'love': 6,
 'chocolate': 7,
 'bunnies': 8,
 'hate': 9,
 'onions': 10}

In [5]:
data = pad_sequences(sequences)
data

array([[ 1,  3,  4,  2,  5],
       [ 1,  6,  7,  2,  8],
       [ 0,  0,  1,  9, 10]], dtype=int32)

In [6]:
data = pad_sequences(sequences, padding = "post")
data

array([[ 1,  3,  4,  2,  5],
       [ 1,  6,  7,  2,  8],
       [ 1,  9, 10,  0,  0]], dtype=int32)

# Embeddings

In [ ]:
model = nn.Sequential(
    nn.Embedding(2000, 5)
)

model()

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not dict

In [12]:
import torch

torch.Tensor(data)

tensor([[ 1.,  3.,  4.,  2.,  5.],
        [ 1.,  6.,  7.,  2.,  8.],
        [ 1.,  9., 10.,  0.,  0.]])

In [16]:
tokenizer.word_index

{'i': 1,
 'and': 2,
 'like': 3,
 'eggs': 4,
 'ham': 5,
 'love': 6,
 'chocolate': 7,
 'bunnies': 8,
 'hate': 9,
 'onions': 10}